// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfsGGM3_Q5iYz-_DWXNcTybNES-QXFXo',
    appId: '1:651529005645:web:724764af7a4637cf968a04',
    messagingSenderId: '651529005645',
    projectId: 'mood-1e181',
    authDomain: 'mood-1e181.firebaseapp.com',
    storageBucket: 'mood-1e181.firebasestorage.app',
    measurementId: 'G-DZFP0CRPEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEHCbZb4WIm-7lDiZZjfG0w6-h5WEzlE',
    appId: '1:651529005645:android:322f59b02fda864a968a04',
    messagingSenderId: '651529005645',
    projectId: 'mood-1e181',
    storageBucket: 'mood-1e181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9Q4lzH8kkm1Cyxhmjpnvyg30YcLEEb4',
    appId: '1:651529005645:ios:ed2d5f1d72808469968a04',
    messagingSenderId: '651529005645',
    projectId: 'mood-1e181',
    storageBucket: 'mood-1e181.firebasestorage.app',
    iosBundleId: 'com.example.mood01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9Q4lzH8kkm1Cyxhmjpnvyg30YcLEEb4',
    appId: '1:651529005645:ios:ed2d5f1d72808469968a04',
    messagingSenderId: '651529005645',
    projectId: 'mood-1e181',
    storageBucket: 'mood-1e181.firebasestorage.app',
    iosBundleId: 'com.example.mood01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnfsGGM3_Q5iYz-_DWXNcTybNES-QXFXo',
    appId: '1:651529005645:web:ffc21190fda8bd96968a04',
    messagingSenderId: '651529005645',
    projectId: 'mood-1e181',
    authDomain: 'mood-1e181.firebaseapp.com',
    storageBucket: 'mood-1e181.firebasestorage.app',
    measurementId: 'G-MH65R8GP5T',
  );
}
